version: '3.5'
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ../../grafana:/etc/grafana
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 
    ports:
      - '9090:9090'
    network_mode: host

  grafana:
    image: grafana/grafana
    container_name: grafana  
    restart: always
    volumes:
      - ./config/grafana:/etc/grafana
    ports:
      - '3000:3000'
    environment:
     - GF_SECURITY_ADMIN_PASSWORD:secret
    network_mode: host
