[package]
description = "OpenEthereum RPC Client"
repository = "https://github.com/openethereum/openethereum"
license = "GPL-3.0"
name = "parity-rpc-client"
version = "1.4.0"
authors = ["Parity <admin@parity.io>"]

[dependencies]
ethereum-types = "0.9.0"
futures = "0.1"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
url = "2.1.1"
matches = "0.1"
parking_lot = "0.10.0"
jsonrpc-core = { git = "https://github.com/adria0/jsonrpc", branch="adria0/rawapi"} 
jsonrpc-ws-server = { git = "https://github.com/adria0/jsonrpc", branch="adria0/rawapi"}
parity-rpc = { path = "../../rpc" }
keccak-hash = "0.5.0"
