[package]
description = "Fetch current ETH price"
repository = "https://github.com/openethereum/openethereum"
license = "GPL-3.0"
name = "price-info"
version = "1.12.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
fetch = { path = "../../util/fetch" }
futures = "0.1"
log = "0.4"
parity-runtime = { git = "https://github.com/vorot93/parity-common", branch = "tokio-compat" }
serde_json = "1.0"

[dev-dependencies]
fake-fetch = { path = "../../util/fake-fetch" }
parity-runtime = { git = "https://github.com/vorot93/parity-common", branch = "tokio-compat", features = ["test-helpers"] }
