[package]
description = "OpenEthereum Common Types"
name = "common-types"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
derive_more = "0.99"
ethbloom = "0.8.0"
ethcore-io = { path = "../../util/io" }
ethereum-types = "0.8.0"
ethjson = { path = "../../json" }
keccak-hash = "0.4.0"
parity-bytes = "0.1"
parity-crypto = { version = "0.5.0", features = ["publickey"] }
parity-util-mem = "0.5.1"
parity-snappy = "0.1"
patricia-trie-ethereum = { path = "../../util/patricia-trie-ethereum" }
rlp = "0.4.0"
rlp-derive = "0.1"
unexpected = { path = "../../util/unexpected" }
vm = { path = "../vm"}

[dev-dependencies]
rustc-hex = "2.1.0"

[features]
test-helpers = []
